### ISSUE TITLE
error on update then nothing plays

### ISSUE THREAD

**Issue by r1kk** [EragonJ/Kaku#551]
#### Bug

after start it says updating then update ok. after no video plays just loading spinner

#### Steps to reproduce the bug

just start

#### What is your Kaku version?

2.0.2-1

#### What is your OS (with version number)?

Linux 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64

#### Which platform are you using to listen to music?

YouTube (for example)

#### Which track format are you using?

best video

#### Is there any error coming from Inspector?

inspector doesnt work

$ kaku
Checking for update
Error: TypeError: this.app.whenReady is not a function
    at ElectronAppAdapter.whenReady (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/ElectronAppAdapter.ts:9:21)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:337:20
    at Generator.next (<anonymous>)
    at AppImageUpdater.getUpdateInfoAndProvider (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at EventEmitter.ipcMain.on (/usr/share/kaku-bin/resources/app.asar/bootup.js:175:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at EventEmitter.ipcMain.on (/usr/share/kaku-bin/resources/app.asar/bootup.js:175:21)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/usr/share/kaku-bin/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
Unhandled rejection TypeError: this.app.whenReady is not a function
    at ElectronAppAdapter.whenReady (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/ElectronAppAdapter.ts:9:21)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:337:20
    at Generator.next (<anonymous>)
    at AppImageUpdater.getUpdateInfoAndProvider (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at EventEmitter.ipcMain.on (/usr/share/kaku-bin/resources/app.asar/bootup.js:175:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/usr/share/kaku-bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at EventEmitter.ipcMain.on (/usr/share/kaku-bin/resources/app.asar/bootup.js:175:21)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/usr/share/kaku-bin/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

#### Others

Feel free to point out any missing points here :) thanks!

**Comment by EragonJ** [comment]
maybe you can try to do force update from settings page ? give it a try ?

**Comment by r1kk** [comment]
At startup notification says Autoupdating core modules..., then a few seconds Done! You can play music.
If I start any video only loading spinner appears over video.
If I go settings > update = Something went wrong...

**Comment by EragonJ** [comment]
ok thanks @r1kk ! I'll check it later :)

**Comment by divyanshu-in** [comment]
I'm also facing same problem, my os is xubuntu 20.04, is there any fix found yet?

**Comment by sainak** [comment]
yup same thing on arch linux version 5.8.13-arch1-1

**Comment by EragonJ** [comment]
not yet, but i'll take a look again, sorry :'(

**Comment by divyanshu-in** [comment]
btw I looked over internet for solution and some people were saying it happens because maybe protonjs dependency you are using is outdated or something.

**Comment by EragonJ** [comment]
@divyanshu-in thanks for the info. I'll put this into notes.

**Comment by tylerecouture** [comment]
Same problem Ubuntu 20.04.1

**Comment by sosaheri** [comment]
the same elementary os

**Comment by K-mikaZ** [comment]
the same on MXLinux

`Linux 5.6.0-2-amd64 # 1 SMP Debian 5.6.14-2~mx19+1 (2020-06-14) x86_64
`
cannot access console from the deb ( I took the appimage and was able to take a screenshot of the console )

![99577921-545f2e80-29dc-11eb-9447-0d6b1e21783a](https://user-images.githubusercontent.com/35837568/99584450-406bfa80-29e5-11eb-962b-a9cbb552201b.png)

Apparently, update Electron would fix auto-updater ( [electron-builder > 20.35.0 requires Electron 3](https://github.com/electron-userland/electron-builder/issues/3505#issuecomment-442156509) )
