### ISSUE TITLE
[debian 64bits] Kaku does not start reading.

### ISSUE THREAD

**Issue by K-mikaZ** [EragonJ/Kaku#554]
#### Bug

the application does not start reading

```
Checking for update
Error: TypeError: this.app.whenReady is not a function
```

#### What is your Kaku version?

debian 2.0.2

#### What is your OS (with version number)?

Linux 5.6.0-2-amd64 # 1 SMP Debian 5.6.14-2~mx19+1 (2020-06-14) x86_64

#### Which platform are you using to listen to music?

YouTube

#### Which track format are you using?

best video and best audio

#### Is there any error coming from Inspector?

cannot access it ( I took the appimage and was able to take a screenshot of the console )

#### Others

`"/opt/Kaku/kaku" %U`
```
Checking for update
Error: TypeError: this.app.whenReady is not a function
    at ElectronAppAdapter.whenReady (/opt/Kaku/resources/app.asar/node_modules/electron-updater/src/ElectronAppAdapter.ts:9:21)
    at /opt/Kaku/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:337:20
    at Generator.next (<anonymous>)
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Kaku/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Kaku/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)....
```
![kaky_bug](https://user-images.githubusercontent.com/35837568/99577921-545f2e80-29dc-11eb-9447-0d6b1e21783a.png)

**Comment by K-mikaZ** [comment]
duplicate, seen too late
Post on [error on update then nothing plays #551](https://github.com/EragonJ/Kaku/issues/551#issuecomment-729936746)
