### ISSUE TITLE
Randomly get this error message when playing track.

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#89]
```bash
Uncaught (in promise) TypeError: Cannot read property 'medium' of undefined
    at render (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/components/shared/track.js:122:55)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:6925:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:6951:14)
    at wrapper [as _renderValidatedComponent] (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:13371:21)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:6385:30)
    at wrapper [as mountComponent] (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:13371:21)
    at Object.ReactReconciler.mountComponent (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:14072:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:13023:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:12929:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (file:///Users/EragonJ/workspace/Kaku/app/dist/frontend/vendor/react/react.js:12874:14)
```

Forgot which track I was listening, but based on the log, it seems that we just need to add more check to avoid this error.

**Comment by mimi89999** [comment]
#65

**Comment by EragonJ** [comment]
Not sure whether this still exists or not, feel free to re-open when this error does happen again.
